apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johnmanjiro13/argo-cd-helmfile-example.git
    targetRevision: additional-resources
    path: nginx/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: nginx
      namespace: app
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
