apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-apps
spec:
  source:
    path: nginx
    repoURL: git@github.com:johnmanjiro13/argo-cd-helmfile-example.git
    targetRevision: main
