apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  creationTimestamp: null
  name: echo
  namespace: nginx  
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - sh
        - -c
        - "sleep 10 && echo hoge"
        image: busybox
        name: echo
        resources: {}
      restartPolicy: Never
status: {}
