apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd
  source:
    path: apps/overlays/staging
    repoURL: git@github.com:johnmanjiro13/argo-cd-helmfile-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
